import { NITRIC_BOOST_AFFILIATE_URL } from "./affiliate-links";
import type { LandingPageConfig } from "./landing-pages";

const NITRIC_BOOST_CTA = NITRIC_BOOST_AFFILIATE_URL;

export const LANDING_PAGES_NITRIC_BOOST: LandingPageConfig[] = [
  {
    slug: "nitric-boost-lp1",
    brandName: "Nitric Boost",
    productName: "Nitric Boost Ultra",
    ctaUrl: NITRIC_BOOST_CTA,
    seoTitle: "Nitric Boost Ultra — Support Performance From $49/Jar",
    seoDescription:
      "Nitric Boost Ultra: nitric oxide powder with L-Arginine, Beet Root & 6 more actives. 1 scoop daily. Bulk from $49/jar, 60-day guarantee, 2 free bonuses on 3+ jars.",
    theme: {
      primary: "#0c3d6e",
      primaryDark: "#072847",
      accent: "#00b4d8",
      accentHover: "#0096c7",
      accentText: "#072847",
      heroBg: "linear-gradient(165deg, #0c3d6e 0%, #1565a8 55%, #0c3d6e 100%)",
      sectionBg: "#eef6fc",
      cardBg: "#ffffff",
      border: "#b8d4ea",
      text: "#1a1a1a",
      muted: "#5a6b78",
    },
    urgencyHeadline: "WAIT — Your Nitric Boost bulk discount is still reserved",
    heroHeadline: "Don't Just Get By — Dominate. Unleash Your Full Potential.",
    heroSubheadline:
      "One scoop of Nitric Boost Ultra daily supports nitric oxide pathways for circulation, stamina, and everyday vitality — not a prescription product.",
    heroBullets: [
      "One scoop per day — mix with water, smoothie, or tea",
      "Bulk tiers from ~$49/jar with free US shipping on 3+ jars",
      "2 FREE bonuses on 3- and 6-jar orders (per official offer)",
      "60-day 100% money-back guarantee — even empty containers",
    ],
    hookParagraphs: [
      "Many men look for better circulation and stamina without adding another pill to the stack. Nitric oxide helps blood vessels relax and expand — the same pathway athletes target for pumps and endurance.",
      "Nitric Boost Ultra combines nitrates and amino acids that convert into nitric oxide (NO), antioxidants that support nitric oxide synthase, and botanicals framed for circulation and daily drive — in one refreshing powder.",
      "This page mirrors the official bundle structure on getnitricboost.com — 1, 3, and 6-jar tiers with the same savings math — so you can compare packages before checkout.",
    ],
    problemTitle: "Why Single-Ingredient NO Boosters Fall Short",
    problemBullets: [
      "One amino acid alone may not deliver the nitrate + antioxidant synergy a full formula provides",
      "Poor NO production can mean vessels do not expand as efficiently during training or long days",
      "Stimulant-heavy shortcuts deliver a spike, not sustained stamina through the afternoon",
      "Under-dosed proprietary blends hide whether you are getting meaningful amounts of key actives",
    ],
    solutionTitle: "Nitric Boost Ultra: One Scoop, Full NO Pathway Support",
    solutionParagraphs: [
      "Every scoop delivers Beet Root nitrates, L-Arginine and L-Citrulline for NO conversion, Horny Goat Weed and Dong Quai for circulation framing, Ginkgo for vessel protection, D-Aspartic Acid for drive support, and Niacin for enhanced blood flow.",
      "Official copy recommends 3–6 months of daily use for the best experience — Stage 1 brings energy clarity, Stage 2 adds stamina, Stage 3 solidifies results for men who stay consistent.",
      "Order through the official checkout and you're covered by the same 60-day, no-questions-asked guarantee advertised on getnitricboost.com.",
    ],
    ingredientsTitle: "Inside Every Scoop of Nitric Boost Ultra",
    ingredients: [
      { name: "Beet Root Powder", benefit: "High nitrate levels that convert into nitric oxide for blood flow" },
      { name: "L-Arginine", benefit: "Amino acid precursor that relaxes blood vessels via NO production" },
      { name: "L-Citrulline DL-Malate", benefit: "Boosts NO levels while malate supports energy production" },
      { name: "Horny Goat Weed", benefit: "Traditional botanical framed for vitality support" },
      { name: "Ginkgo Biloba", benefit: "Antioxidant protection for blood vessels and circulation" },
      { name: "D-Aspartic Acid", benefit: "Supports luteinizing hormone and testosterone pathways" },
      { name: "Dong Quai", benefit: "Traditional botanical for improved blood flow" },
      { name: "Niacin (B3)", benefit: "Vasodilation support for healthy circulation" },
    ],
    benefitsTitle: "What Men Buy Nitric Boost Ultra For",
    benefits: [
      "Steadier stamina and drive through demanding days",
      "Surge of daily confidence from improved circulation support",
      "Enhanced gym pumps and recovery from improved blood flow",
      "Cleaner energy without stimulant jitters or afternoon crash",
      "Simple once-daily ritual — one scoop, any beverage",
    ],
    testimonials: [
      {
        name: "Steve W.",
        location: "Phoenix, Arizona",
        quote:
          "Nitric Boost is tasty and easy to stick with. I have more afternoon energy and my workouts feel stronger — my wife noticed the mood shift before I did.",
        packageLabel: "6 jars",
      },
      {
        name: "David S.",
        location: "Houston, Texas",
        quote:
          "I wanted better circulation without another pill. After a few weeks on Nitric Boost I feel more consistent energy and less crash after work.",
        packageLabel: "6 jars",
      },
      {
        name: "Michael H.",
        location: "Tampa, Florida",
        quote:
          "The powder mixes fast and I actually look forward to it. Gym pumps improved and I feel sharper through long days — results not overnight, but real for me.",
        packageLabel: "6 jars",
      },
    ],
    productMeta: {
      heroBottleCount: 1,
      galleryTitle: "Daily Ritual · Circulation Support",
    },
    guaranteeTitle: "100% Satisfaction 60-Day Money Back Guarantee",
    guaranteeParagraphs: [
      "Order any amount — one, three, or six jars — and you're covered for 60 full days. Not thrilled? Call or email support, say you'd like a refund, and get every penny back per vendor terms.",
      "No reason required. Use every scoop or never open the container — the guarantee stands either way on official orders.",
    ],
    packages: [
      {
        id: "basic",
        title: "Basic",
        subtitle: "30-day supply · 1 jar",
        pricePerBottle: "$69",
        total: "$69",
        regularTotal: "$199",
        savings: "Save $130",
        shipping: "+ shipping",
        ctaLabel: "Try 1 Jar",
      },
      {
        id: "popular",
        title: "Most Popular",
        subtitle: "90-day supply · 3 jars",
        pricePerBottle: "$59",
        total: "$177",
        regularTotal: "$597",
        savings: "Save $420",
        badge: "2 FREE BONUSES · FREE US SHIPPING",
        shipping: "Free US shipping",
        highlight: true,
        ctaLabel: "Claim 3-Jar Bundle",
      },
      {
        id: "best",
        title: "Best Value",
        subtitle: "180-day supply · 6 jars",
        pricePerBottle: "$49",
        total: "$294",
        regularTotal: "$1,194",
        savings: "Save $900",
        badge: "BIGGEST DISCOUNT · 2 FREE BONUSES",
        shipping: "Free US shipping",
        ctaLabel: "Claim 6-Jar Bundle",
      },
    ],
    faq: [
      {
        q: "How do I take Nitric Boost Ultra?",
        a: "Take 1 scoop with a glass of water daily — or mix into a smoothie or tea. The proprietary blend goes to work immediately per official directions.",
      },
      {
        q: "Is Nitric Boost safe?",
        a: "Soy-free, dairy-free, vegetarian, non-GMO, third-party inspected, and manufactured in a GMP-certified US facility. Consult your doctor before starting any supplement.",
      },
      {
        q: "How many jars should I order?",
        a: "Official guidance recommends 3–6 months of consistent use. The 6-jar package offers the lowest per-jar cost plus two free bonuses and free US shipping.",
      },
      {
        q: "What if it doesn't work for me?",
        a: "Every order includes a 60-day no-questions-asked money-back guarantee — return even empty containers for a full refund.",
      },
    ],
    finalCtaHeadline: "Claim Your Discounted Nitric Boost Before Pricing Resets",
  },
  {
    slug: "nitric-boost-lp2",
    variant: "lp2",
    lp2Style: "advertorial",
    brandName: "Nitric Boost",
    productName: "Nitric Boost Ultra",
    ctaUrl: NITRIC_BOOST_CTA,
    seoTitle: "Nitric Boost Ultra Review — Nitric Oxide Powder Explained",
    seoDescription:
      "Breakdown of Nitric Boost Ultra: nitric oxide support, ingredient stack, and official bundle pricing from $49/jar. Not a prescription product.",
    theme: {
      primary: "#0c3d6e",
      primaryDark: "#072847",
      accent: "#0077b6",
      accentHover: "#005f92",
      accentText: "#ffffff",
      heroBg: "#f8fafc",
      sectionBg: "#eef6fc",
      cardBg: "#ffffff",
      border: "#cbd5e1",
      text: "#1e293b",
      muted: "#64748b",
    },
    urgencyHeadline: "Official site still offering bulk pricing + 2 free bonuses on 3+ jars",
    heroHeadline: "Nitric Boost Ultra: How a Daily NO Powder Frames Circulation Support",
    heroSubheadline:
      "A nitric oxide powder built around beet nitrates, amino acids, and circulation botanicals — for men who want stamina and blood-flow support without adding another pill.",
    heroBullets: [
      "Supports nitric oxide pathways for circulation and daily stamina",
      "8-ingredient powder: Beet Root, L-Arginine, L-Citrulline & more",
      "Bulk from $49/jar · free US shipping on 3- and 6-jar orders",
      "60-day empty-container guarantee on official checkout",
    ],
    hookParagraphs: [
      "Nitric oxide is how your body signals blood vessels to relax and expand — the same pathway tied to gym pumps, endurance, and daily stamina.",
      "Nitric Boost Ultra stacks beet-root nitrates, L-arginine, L-citrulline, and circulation botanicals in one scoop — positioned as dietary supplement support, not a drug.",
      "Men planning a fair trial should budget 90–180 days on larger jars, matching official guidance on getnitricboost.com.",
      "We traced pricing on getnitricboost.com so readers can access the same 1-, 3-, and 6-jar tiers — including two free digital bonuses on larger orders.",
    ],
    problemTitle: "Why Under-Dosed NO Products Disappoint",
    problemBullets: [
      "Single amino acids miss the nitrate + antioxidant synergy many formulas advertise",
      "Declining nitric oxide can mean vessels do not dilate efficiently during training or long workdays",
      "Stimulant shortcuts spike energy, then crash — not the steady support many men want",
      "Buy only from the official site if you want the formula and guarantee in vendor terms",
    ],
    solutionTitle: "One Scoop Daily: The Nitric Boost Ultra Protocol",
    solutionParagraphs: [
      "Nitric Boost Ultra combines Beet Root nitrates, L-Arginine, L-Citrulline DL-Malate, Horny Goat Weed, Ginkgo Biloba, Dong Quai, D-Aspartic Acid, and Niacin in a daily powder — manufactured in the USA with GMP certification per official copy.",
      "Men planning a fair trial should budget 90–180 days on the 3- or 6-jar tiers — the same packages 87% of customers choose for free shipping and bonus access.",
    ],
    ingredientsTitle: "Ingredient Breakdown — What Each Scoop Delivers",
    ingredients: [
      { name: "Beet Root Powder", benefit: "Nitrate concentrate converts to nitric oxide for circulation" },
      { name: "L-Arginine", benefit: "Direct NO precursor that relaxes and expands blood vessels" },
      { name: "L-Citrulline DL-Malate", benefit: "Sustained NO elevation plus malate-driven energy support" },
      { name: "Horny Goat Weed", benefit: "Traditional botanical framed for vitality support" },
      { name: "Ginkgo Biloba", benefit: "Antioxidant vessel protection" },
      { name: "D-Aspartic Acid", benefit: "LH and testosterone pathway support" },
      { name: "Dong Quai", benefit: "Traditional blood flow botanical" },
      { name: "Niacin", benefit: "B3 vasodilation for circulation support" },
    ],
    benefitsTitle: "What Verified Purchasers Report",
    benefits: [
      "Renewed stamina and daily confidence",
      "Steadier energy through workouts and long workdays",
      "Better gym pumps from enhanced blood flow",
      "Simpler morning ritual — powder instead of another capsule",
      "Tasty daily mix — water, smoothie, or tea",
    ],
    timeline: [
      {
        milestone: "Week 1–2",
        title: "NO pathway activation",
        body: "Many men report early shifts in energy and mental clarity as nitric oxide levels respond to daily nitrates and amino acids.",
      },
      {
        milestone: "Month 1–2",
        title: "Stamina & drive",
        body: "Official copy describes Stage 2 as improved stamina and training output — individual results vary.",
      },
      {
        milestone: "Month 3+",
        title: "Results solidify",
        body: "Three to six months of consistency aligns with official guidance for a full assessment of energy and drive.",
      },
    ],
    testimonials: [
      {
        name: "Steve Wilson",
        location: "Phoenix, Arizona",
        quote:
          "Easy to stick with every morning. More afternoon energy and better gym pumps — my wife noticed the mood lift first.",
        packageLabel: "6 jars",
      },
      {
        name: "David Silver",
        location: "Houston, Texas",
        quote:
          "I wanted circulation support without another pill. Steadier energy after a few weeks — not overnight, but consistent for me.",
        packageLabel: "6 jars",
      },
      {
        name: "Michael Harris",
        location: "Tampa, Florida",
        quote:
          "Mixes fast, tastes good. I feel sharper on long days and recovery between workouts improved.",
        packageLabel: "6 jars",
      },
    ],
    guaranteeTitle: "60-Day \"No Questions Asked\" Guarantee",
    guaranteeParagraphs: [
      "Every jar order on the official site includes 60 days to test Nitric Boost Ultra. Request a refund anytime — even if you've used every scoop.",
      "Start with one jar if skeptical. Move to 3- or 6-jar bulk once early shifts appear for lowest per-jar cost and free bonuses.",
    ],
    productBadgeLine: "Daily Powder · 30 servings",
    pricingFunnel: {
      layout: "supplement-funnel",
      columnOrder: ["basic", "popular", "best"],
      sectionTitle: "Choose Your Package",
      highlightHeaderBg: "#0077b6",
    },
    packages: [
      {
        id: "basic",
        title: "Basic — 1 Jar",
        subtitle: "30-day supply",
        funnelHeader: "TRY ONE",
        funnelSubheader: "30-Day Supply (1 Jar)",
        pricePerBottle: "$69",
        priceDisplay: "$69",
        total: "$69",
        regularTotal: "$199",
        savingsBurst: "SAVE $130",
        shipping: "+ shipping",
        bottleCount: 1,
        ctaLabel: "ADD TO CART",
      },
      {
        id: "popular",
        title: "Bundle — 3 Jars",
        subtitle: "90-day supply · 2 free bonuses",
        funnelHeader: "MOST POPULAR",
        funnelSubheader: "90-Day Supply (3 Jars)",
        pricePerBottle: "$59",
        priceDisplay: "$177",
        priceSubline: "($59/jar)",
        total: "$177",
        regularTotal: "$597",
        savingsBurst: "SAVE $420",
        badge: "FREE US SHIPPING",
        perkLines: ["FAST & FREE US SHIPPING", "2 FREE BONUSES"],
        shipping: "Free US shipping",
        highlight: true,
        bottleCount: 3,
        ctaLabel: "ADD TO CART",
      },
      {
        id: "best",
        title: "Best Value — 6 Jars",
        subtitle: "180-day supply · 2 free bonuses",
        funnelHeader: "BEST VALUE!",
        funnelSubheader: "180-Day Supply (6 Jars)",
        pricePerBottle: "$49",
        priceDisplay: "$294",
        priceSubline: "($49/jar)",
        total: "$294",
        regularTotal: "$1,194",
        savingsBurst: "SAVE $900",
        badge: "BIGGEST DISCOUNT",
        perkLines: ["BIGGEST DISCOUNT", "FREE US SHIPPING"],
        shipping: "Free US shipping",
        bottleCount: 6,
        ctaLabel: "ADD TO CART",
      },
    ],
    faq: [
      {
        q: "Is Nitric Boost Ultra natural?",
        a: "Yes — soy-free, dairy-free, vegetarian, non-GMO, with plant ingredients and natural minerals per official product copy.",
      },
      {
        q: "What's the best way to take it?",
        a: "One scoop daily with water, smoothie, or tea. Consistency over 3–6 months is key.",
      },
      {
        q: "Are the bonuses really free?",
        a: "Official offer includes The Nitric Boost Blueprint and Marathon Man Stamina guides free on 3- and 6-jar orders.",
      },
      {
        q: "Where should I buy?",
        a: "Only through getnitricboost.com — third-party sellers on Amazon/eBay may sell counterfeits per vendor warnings.",
      },
    ],
    finalCtaHeadline: "See If Nitric Boost Bulk Pricing Is Still Available",
  },
];
