import type { LandingPageConfig } from "./landing-pages";
import { SUPPLEMENT_FACILITY_BULLET, SUPPLEMENT_FACILITY_FAQ } from "./lp-robots";

export const LANDING_PAGES_LP2: LandingPageConfig[] = [
  {
    slug: "critical-t-lp2",
    variant: "lp2",
    lp2Style: "dtc",
    brandName: "Critical T",
    productName: "Critical T",
    ctaUrl:
      "https://9dcacr3eqbms0qez2408eyse51.hop.clickbank.net/?&traffic_source=blog&traffic_type=paid&campaign=t-compare",
    seoTitle: "Critical T — Natural T Support | Official Product Page",
    seoDescription:
      "Shop Critical T: clinically dosed Tongkat Ali, DIM & Acacetin. See the Day 7–90 timeline, ingredient breakdown, and bundle pricing from $55/mo.",
    theme: {
      primary: "#0f172a",
      primaryDark: "#020617",
      accent: "#2563eb",
      accentHover: "#1d4ed8",
      accentText: "#ffffff",
      heroBg: "#ffffff",
      sectionBg: "#f8fafc",
      cardBg: "#ffffff",
      border: "#e2e8f0",
      text: "#0f172a",
      muted: "#64748b",
    },
    urgencyHeadline: "Free shipping unlocked on 3+ bottle orders today",
    heroHeadline: "Support Your Body's Natural Testosterone — Without the Clinic",
    heroSubheadline:
      "Critical T is a two-capsule daily stack built around Tongkat Ali, DIM, and Acacetin — designed for men who want structured hormone support, not random herb blends.",
    heroBullets: [
      "Subscribe from ~$55/mo — transparent bundle math on every tier",
      "Two capsules each morning · no needles · no prescriptions",
      "60-day money-back guarantee per official vendor terms",
      SUPPLEMENT_FACILITY_BULLET,
    ],
    hookParagraphs: [
      "Most men don't need a lecture on low energy — they need a formula that addresses testosterone signaling and estrogen balance together. Critical T was built around that dual-pathway idea.",
      "Unlike single-ingredient boosters, every dose combines three named actives with a clear role: support natural T production, help process excess estrogen, and keep aromatase-related balance in check.",
    ],
    problemTitle: "Why Single-Ingredient Boosters Fall Short",
    problemBullets: [
      "T can rise on paper while usable free T stays flat without estrogen support",
      "TRT costs hundreds per month and requires ongoing clinic management",
      "Proprietary blends hide under-dosed ingredients behind flashy labels",
      "Willpower can't fix biology — consistent daily support can",
    ],
    solutionTitle: "A Calibrated Stack You Can Actually Stick With",
    solutionParagraphs: [
      "Critical T delivers Tongkat Ali for natural testosterone pathway support, DIM for liver-mediated estrogen metabolism, and Acacetin from Turnera diffusa for balance framing competitors skip.",
      "Plan on at least 60 days for a fair trial — most men assessing energy, drive, and gym recovery need that runway before judging results.",
    ],
    ingredientsTitle: "What's Inside Every Serving",
    ingredients: [
      {
        name: "Tongkat Ali",
        benefit: "Supports luteinizing hormone and natural T signaling",
      },
      {
        name: "DIM",
        benefit: "Helps convert excess estrogen into inactive forms",
      },
      {
        name: "Acacetin",
        benefit: "Turnera diffusa extract for aromatase balance support",
      },
    ],
    productMeta: {
      heroTagline: "Natural testosterone support · 60 capsules",
      heroSocialProof: "Join thousands of men on Critical T",
      pricingHeadline: "Official Bundle Pricing",
      stickyCtaLabel: "Add To Cart →",
    },
    productBadgeLine: "Daily Formula · 60 caps",
    pricingFunnel: {
      layout: "supplement-funnel",
      columnOrder: ["starter", "best", "popular"],
      sectionTitle: "Choose Your Package",
    },
    benefitsTitle: "What Consistent Use Can Support",
    benefits: [
      "Clearer morning energy instead of repeated snooze cycles",
      "Better gym output and recovery between sessions",
      "Sharper focus and motivation through the workday",
      "Libido and stamina as part of overall male vitality",
      "A simple daily ritual — no injections or clinic visits",
    ],
    timeline: [
      {
        milestone: "Day 7",
        title: "Early energy shifts",
        body: "Many men report waking easier and feeling less midday drag — subtle, but noticeable when you're paying attention.",
      },
      {
        milestone: "Day 30",
        title: "Training momentum",
        body: "Gym sessions feel more productive. Recovery between workouts often improves as daily consistency compounds.",
      },
      {
        milestone: "Day 90",
        title: "Full assessment window",
        body: "Official guidance recommends 60–90 days for a fair read on drive, stamina, and overall vitality markers.",
      },
    ],
    testimonials: [
      {
        name: "Marcus T.",
        location: "Colorado, USA",
        quote:
          "Clean product page, clear ingredients — I subscribed after comparing three brands. Week two is when I noticed more morning energy.",
        packageLabel: "Subscribe & Save",
      },
      {
        name: "Daniel R.",
        location: "Florida, USA",
        quote:
          "The 90-day bundle made the math easy. Sixty days in, I'm training four days again and not crashing by 8pm.",
        packageLabel: "90-day supply",
      },
      {
        name: "Kevin L.",
        location: "Ohio, USA",
        quote:
          "Best per-capsule cost on the bulk tier. Guarantee meant zero risk running the full trial.",
        packageLabel: "Best value bundle",
      },
    ],
    guaranteeTitle: "60-Day Money-Back Guarantee",
    guaranteeParagraphs: [
      "Try Critical T for 60 days. If you're not satisfied, request a refund per vendor terms — including empty bottles where applicable.",
      "Test it on your schedule, not on a marketing deadline.",
    ],
    packages: [
      {
        id: "starter",
        title: "Subscribe & Save",
        subtitle: "1 bottle · monthly delivery",
        funnelHeader: "STARTER",
        funnelSubheader: "Subscribe & Save (1 Bottle)",
        pricePerBottle: "$55.20",
        priceDisplay: "$55.20/month",
        total: "$55.20/mo",
        shipping: "+ Shipping fee $5.99 · Delivered monthly — cancel anytime",
        bottleCount: 1,
        ctaLabel: "ADD TO CART",
      },
      {
        id: "best",
        title: "Best Value",
        subtitle: "120-day supply · Buy 1 Get 3 Free",
        funnelHeader: "BEST VALUE!",
        funnelSubheader: "120-Day Supply (4 bottles) · Buy 1 Get 3 Free",
        pricePerBottle: "$16.75",
        priceDisplay: "$67",
        priceSubline: "$16.75/bottle",
        total: "$67",
        regularTotal: "$276",
        savingsBurst: "SAVE $209",
        badge: "BIGGEST DISCOUNT",
        perkLines: ["BIGGEST DISCOUNT", "+ $7.99 SHIPPING FEE"],
        shipping: "+ $7.99 shipping fee",
        highlight: true,
        bottleCount: 4,
        ctaLabel: "ADD TO CART",
      },
      {
        id: "popular",
        title: "Most Popular",
        subtitle: "90-day supply · 3 bottles",
        funnelHeader: "MOST POPULAR",
        funnelSubheader: "90-Day Supply (3 Bottles)",
        pricePerBottle: "$59",
        priceDisplay: "$177",
        priceSubline: "($59/bottle)",
        total: "$177",
        regularTotal: "$207",
        savingsBurst: "SAVE $30",
        badge: "FREE US SHIPPING",
        perkLines: ["FAST & FREE SHIPPING"],
        shipping: "Fast & free US shipping",
        bottleCount: 3,
        ctaLabel: "ADD TO CART",
      },
    ],
    faq: [
      {
        q: "How do I take Critical T?",
        a: "Two capsules once daily with water in the morning, with or without food.",
      },
      {
        q: "When will I notice results?",
        a: "Some men feel early energy shifts within two weeks. Allow 60–90 days for a full assessment.",
      },
      {
        q: "Is this TRT?",
        a: "No — Critical T is an OTC dietary supplement supporting natural pathways, not exogenous testosterone.",
      },
      {
        q: "What if it doesn't work for me?",
        a: "You're covered by the 60-day guarantee on the official checkout page.",
      },
    ],
    finalCtaHeadline: "Add Critical T to Your Daily Stack",
  },
  {
    slug: "endopeak24-lp2",
    variant: "lp2",
    lp2Style: "advertorial",
    brandName: "EndoPeak",
    productName: "EndoPeak",
    ctaUrl:
      "https://42ad2cskk5msam5atc1eq2ur5a.hop.clickbank.net/?&traffic_source=blog&traffic_type=paid&campaign=t-compare",
    seoTitle: "EndoPeak Review — 8-Ingredient Men's Vitality Formula Explained",
    seoDescription:
      "Independent-style breakdown of EndoPeak: circulation botanicals, libido support, bulk pricing from $49/bottle, and what men report after 90 days.",
    theme: {
      primary: "#134e4a",
      primaryDark: "#0f3d3a",
      accent: "#14b8a6",
      accentHover: "#0d9488",
      accentText: "#ffffff",
      heroBg: "#faf8f5",
      sectionBg: "#f0fdfa",
      cardBg: "#ffffff",
      border: "#ccfbf1",
      text: "#1c1917",
      muted: "#57534e",
    },
    urgencyHeadline: "Reader offer: bulk pricing still available at official checkout",
    heroHeadline:
      "The 8-Botanical Formula Men Over 40 Are Using Before Considering Prescription Routes",
    heroSubheadline:
      "EndoPeak combines Hawthorn Berry, Tongkat Ali, Epimedium, and five more actives in one daily capsule — here's what the mechanism story actually looks like.",
    heroBullets: [
      "Eight named botanicals — no hidden proprietary blend",
      "Bulk tiers drop to ~$49/bottle with free US shipping",
      "Once-daily capsule after your first meal",
      "60-day empty-bottle guarantee on official orders",
    ],
    hookParagraphs: [
      "If you've read the same testosterone ads a dozen times, you're right to be skeptical. The question isn't whether aging affects stamina — it's whether any daily formula addresses circulation, libido, and stress resilience together.",
      "EndoPeak's structure is what caught our attention: Hawthorn for cardiovascular circulation, Epimedium for blood flow, Tribulus and Tongkat Ali for libido framing, Saw Palmetto for testosterone pathway support, plus Chrysin, Winged Treebine, and Magnesium.",
      "We traced the official funnel pricing so readers can access the same multi-bottle tiers — intro, 90-day, and 180-day — without hunting through pop-ups.",
    ],
    problemTitle: "Why \"Just Push Harder\" Stops Working After 40",
    problemBullets: [
      "Blood flow and stamina decline together — gym and daily confidence share the same biology",
      "Chronic stress accelerates the slide faster than willpower can reverse",
      "Single-ingredient pills miss the synergy multi-botanical stacks aim for",
      "Prescription paths aren't what every man wants as a first step",
    ],
    solutionTitle: "One Capsule, Eight Pathways — No Needles Required",
    solutionParagraphs: [
      "Take EndoPeak with water after breakfast. Per official vendor copy, the formula is manufactured in a US facility registered with the FDA for dietary supplements, using plant ingredients and natural minerals.",
      "Smart buyers often start with the 3-bottle tier for balance between savings and commitment, then move to the 6-bottle bundle at $49/bottle once early shifts appear.",
    ],
    ingredientsTitle: "Ingredient Breakdown",
    ingredients: [
      { name: "Tongkat Ali", benefit: "Male vitality and daily energy support" },
      { name: "Epimedium", benefit: "Blood flow where performance matters" },
      { name: "Saw Palmetto", benefit: "Healthy testosterone production pathways" },
      { name: "Hawthorn Berry", benefit: "Circulation and cardiovascular support" },
      { name: "Tribulus", benefit: "Libido baseline maintenance" },
      { name: "Magnesium", benefit: "Testosterone levels and recovery support" },
      { name: "Chrysin", benefit: "Healthy estrogen balance support" },
      { name: "Winged Treebine", benefit: "Adaptogenic vitality botanical" },
    ],
    productMeta: {
      advertorialMasthead: {
        category: "Men's Health · Formula Review",
        publication: "Vitality Report",
        author: "By Marcus Webb, Health Editor",
      },
      pricingHeadline: "Official EndoPeak Bundle Pricing",
      stickyCtaLabel: "Add To Cart →",
    },
    productBadgeLine: "8 Botanicals · 60 caps",
    pricingFunnel: {
      layout: "supplement-funnel",
      columnOrder: ["intro", "popular", "best"],
      sectionTitle: "Choose Your Package",
      highlightHeaderBg: "#d4a017",
      footerNote: "Secure checkout · Official EndoPeak tiers · 60-day empty-bottle guarantee",
    },
    benefitsTitle: "What Men Report After Staying Consistent",
    benefits: [
      "Usable energy from morning through evening — not a 2-hour stimulant spike",
      "Stronger sessions with faster bounce-back between workouts",
      "Renewed confidence in intimate situations",
      "Calmer stress response from adaptogenic botanicals",
      "Simple once-daily ritual — no clinic waiting rooms",
    ],
    timeline: [
      {
        milestone: "Week 1",
        title: "First signals",
        body: "Many users report subtle energy and mood shifts within the first seven days.",
      },
      {
        milestone: "Month 1",
        title: "Consistency pays",
        body: "Stamina and recovery often improve as daily use compounds.",
      },
      {
        milestone: "Month 3",
        title: "Fair trial complete",
        body: "Official guidance recommends 90 days before judging full results.",
      },
    ],
    testimonials: [
      {
        name: "Thomas J.",
        location: "Arizona, USA",
        quote:
          "I work finance — used to take forever to unwind. EndoPeak changed that timeline. My wife noticed before I did.",
        packageLabel: "180-day supply",
      },
      {
        name: "Chad B.",
        location: "Texas, USA",
        quote:
          "Self-conscious about performance for years. Stamina and confidence came back — this isn't hype copy, it's my experience.",
        packageLabel: "90-day supply",
      },
      {
        name: "Jason S.",
        location: "North Carolina, USA",
        quote:
          "Two weeks in I felt like my 20s again. Workouts stronger, energy through the roof.",
        packageLabel: "6-bottle package",
      },
    ],
    guaranteeTitle: "60-Day Empty-Bottle Guarantee",
    guaranteeParagraphs: [
      "Try EndoPeak for 60 days. Not satisfied? Request a refund per official terms — even if bottles are empty.",
      "Start with the tier that fits your budget; upgrade once you feel the difference.",
    ],
    packages: [
      {
        id: "intro",
        title: "Try Two",
        subtitle: "60-day supply · 2 bottles",
        funnelHeader: "TRY TWO",
        funnelSubheader: "60-Day Supply (2 Bottles)",
        pricePerBottle: "$69",
        priceDisplay: "$138",
        priceSubline: "($69/bottle)",
        total: "$138",
        shipping: "+ shipping fee",
        bottleCount: 2,
        ctaLabel: "ADD TO CART",
      },
      {
        id: "popular",
        title: "Most Popular",
        subtitle: "90-day supply · 3 bottles",
        funnelHeader: "MOST POPULAR",
        funnelSubheader: "90-Day Supply (3 Bottles)",
        pricePerBottle: "$59",
        priceDisplay: "$177",
        priceSubline: "($59/bottle)",
        total: "$177",
        regularTotal: "$537",
        savingsBurst: "SAVE $360",
        badge: "FREE US SHIPPING",
        perkLines: ["FAST & FREE US SHIPPING"],
        shipping: "Free US shipping",
        highlight: true,
        bottleCount: 3,
        ctaLabel: "ADD TO CART",
      },
      {
        id: "best",
        title: "Best Value",
        subtitle: "180-day supply · 6 bottles",
        funnelHeader: "BEST VALUE!",
        funnelSubheader: "180-Day Supply (6 Bottles)",
        pricePerBottle: "$49",
        priceDisplay: "$294",
        priceSubline: "($49/bottle)",
        total: "$294",
        regularTotal: "$1,074",
        savingsBurst: "SAVE $780",
        badge: "LOWEST PRICE",
        perkLines: ["BIGGEST DISCOUNT", "FREE US SHIPPING"],
        shipping: "Free US shipping",
        bottleCount: 6,
        ctaLabel: "ADD TO CART",
      },
    ],
    faq: [
      {
        q: "How do I take EndoPeak?",
        a: "One capsule daily with water after your first meal.",
      },
      {
        q: "When will I see results?",
        a: "Many users feel initial shifts within a week. Allow 3 months for the best experience.",
      },
      {
        q: "Is EndoPeak safe?",
        a: SUPPLEMENT_FACILITY_FAQ,
      },
      {
        q: "Which package should I choose?",
        a: "First-timers: 3-bottle tier. Lowest per-bottle cost: 6-bottle bundle with free shipping.",
      },
    ],
    finalCtaHeadline: "See If EndoPeak Is Still In Stock at Official Pricing",
  },
  {
    slug: "erecprime24-lp2",
    variant: "lp2",
    lp2Style: "bento",
    brandName: "ErecPrime",
    productName: "ErecPrime",
    ctaUrl:
      "https://erecprime24.com/c/order-now.php?hop=sorela1&hopId=976f8585-4681-4e04-8126-a9a68e7c372b&&traffic_source=blog&traffic_type=paid&campaign=t-compare",
    seoTitle: "ErecPrime — Performance Formula | Modern Men's Stack",
    seoDescription:
      "ErecPrime: 8-ingredient daily capsule for stamina, blood flow & drive. From $49/bottle on bulk. 60-day guarantee.",
    theme: {
      primary: "#fafafa",
      primaryDark: "#0a0a0a",
      accent: "#ff4757",
      accentHover: "#ee5a6f",
      accentText: "#ffffff",
      heroBg: "#0a0a0a",
      sectionBg: "#141414",
      cardBg: "#1a1a1a",
      border: "#2a2a2a",
      text: "#fafafa",
      muted: "#a1a1aa",
    },
    urgencyHeadline: "Bulk tiers from $49/bottle — limited checkout slots",
    heroHeadline: "Perform Better. Feel Stronger. One Capsule.",
    heroSubheadline:
      "Eight premium botanicals targeting circulation, libido, and testosterone pathways — built for men who want results without stimulant crashes.",
    heroBullets: [
      "Trial from $69 · bulk drops to ~$49/bottle",
      "Free US shipping on 3- and 6-bottle orders",
      "60-day money-back guarantee",
      "Plant-based · non-GMO capsules",
    ],
    hookParagraphs: [
      "Performance isn't one-dimensional. Blood flow, stamina, stress, and hormone balance all intersect — and ignoring any leg of the stack leaves results on the table.",
      "ErecPrime targets the full equation: Hawthorn and Epimedium for circulation, Tribulus and Tongkat Ali for libido, Saw Palmetto and Magnesium for testosterone support.",
    ],
    problemTitle: "Why Generic Men's Formulas Fail",
    problemBullets: [
      "Proprietary blends hide doses — you never know what you're getting",
      "Stimulant-heavy pills crash hard by afternoon",
      "Circulation ignored = half the performance equation missing",
      "Waiting costs months of confidence you won't recover",
    ],
    solutionTitle: "The Full Performance Stack in One Ritual",
    solutionParagraphs: [
      "One capsule after breakfast. Eight synergistic ingredients. No jitters — sustained support framed around the official funnel's verified purchaser feedback.",
      "Skeptical? Start with one bottle. Committed? The 6-bottle tier delivers lowest per-unit cost with free shipping.",
    ],
    ingredientsTitle: "8 Actives. Zero Fillers Story.",
    ingredients: [
      { name: "Tongkat Ali", benefit: "Male vitality and daily energy support" },
      { name: "Epimedium", benefit: "Circulation support botanical" },
      { name: "Saw Palmetto", benefit: "Testosterone production support" },
      { name: "Hawthorn Berry", benefit: "Healthy circulation" },
      { name: "Tribulus", benefit: "Libido baseline" },
      { name: "Magnesium", benefit: "T-levels and muscle function" },
      { name: "Chrysin", benefit: "Estrogen balance support" },
      { name: "Winged Treebine", benefit: "Vitality adaptogen framing" },
    ],
    productMeta: {
      heroTagline: "8 botanicals · one capsule daily",
      heroBottleCount: 1,
      stickyCtaLabel: "Add To Cart →",
    },
    productBadgeLine: "8 Botanicals · 60 caps",
    pricingFunnel: {
      layout: "supplement-funnel",
      columnOrder: ["intro", "popular", "best"],
      sectionTitle: "Pick Your Stack",
      highlightHeaderBg: "#ff4757",
      footerNote: "Secure checkout · Official ErecPrime bundle tiers · 60-day guarantee",
    },
    benefitsTitle: "Built For Men Who Want More",
    benefits: [
      "Steadier stamina through long workdays",
      "Cleaner daily energy — no afternoon crash",
      "Circulation support framed around the eight-botanical stack",
      "Gym performance that matches how you want to feel after work",
      "Compound confidence from consistent action",
    ],
    timeline: [
      {
        milestone: "Stage 1",
        title: "Energy & sleep",
        body: "First weeks often bring cleaner mornings and better sleep quality.",
      },
      {
        milestone: "Stage 2",
        title: "Stamina & drive",
        body: "Weeks 4–8: many men report stamina and daily energy improvements.",
      },
      {
        milestone: "Stage 3",
        title: "Results solidify",
        body: "90-day runway recommended before full assessment.",
      },
    ],
    testimonials: [
      {
        name: "Mark B.",
        location: "New York, USA",
        quote:
          "Thought my best days were gone. Back in my prime — more energy after work and better mood at home.",
        packageLabel: "90-day supply",
      },
      {
        name: "Thomas J.",
        location: "Arizona, USA",
        quote:
          "One capsule with coffee every morning. Afternoon crash is gone — my wife noticed before I did.",
        packageLabel: "180-day supply",
      },
      {
        name: "Chad B.",
        location: "Texas, USA",
        quote:
          "Stamina, confidence, no jitters. It became part of my morning routine.",
        packageLabel: "6-bottle package",
      },
    ],
    guaranteeTitle: "60-Day 100% Money-Back Guarantee",
    guaranteeParagraphs: [
      "Use ErecPrime up to 60 days. Not thrilled? Refund per vendor terms — even empty bottles.",
      "The only way to know is to test it on your body.",
    ],
    packages: [
      {
        id: "intro",
        title: "Try One",
        subtitle: "30-day · 1 bottle",
        funnelHeader: "TRY ONE",
        funnelSubheader: "30-Day Supply (1 Bottle)",
        pricePerBottle: "$69",
        priceDisplay: "$69",
        total: "$69",
        regularTotal: "$179",
        savingsBurst: "SAVE $110",
        shipping: "+ shipping fee",
        bottleCount: 1,
        ctaLabel: "ADD TO CART",
      },
      {
        id: "popular",
        title: "Most Popular",
        subtitle: "90-day · 3 bottles",
        funnelHeader: "MOST POPULAR",
        funnelSubheader: "90-Day Supply (3 Bottles)",
        pricePerBottle: "$59",
        priceDisplay: "$177",
        priceSubline: "($59/bottle)",
        total: "$177",
        regularTotal: "$537",
        savingsBurst: "SAVE $360",
        badge: "FREE SHIPPING",
        perkLines: ["FAST & FREE US SHIPPING"],
        shipping: "Free US shipping",
        highlight: true,
        bottleCount: 3,
        ctaLabel: "ADD TO CART",
      },
      {
        id: "best",
        title: "Best Value",
        subtitle: "180-day · 6 bottles",
        funnelHeader: "BEST VALUE!",
        funnelSubheader: "180-Day Supply (6 Bottles)",
        pricePerBottle: "$49",
        priceDisplay: "$294",
        priceSubline: "($49/bottle)",
        total: "$294",
        regularTotal: "$1,074",
        savingsBurst: "SAVE $780",
        badge: "MAX SAVINGS",
        perkLines: ["BIGGEST DISCOUNT", "FREE US SHIPPING"],
        shipping: "Free US shipping",
        bottleCount: 6,
        ctaLabel: "ADD TO CART",
      },
    ],
    faq: [
      {
        q: "How should I take ErecPrime?",
        a: "One capsule daily with water after your first meal.",
      },
      {
        q: "Is ErecPrime natural?",
        a: "Plant ingredients and natural minerals. No synthetic hormones.",
      },
      {
        q: "How long should I try it?",
        a: "At least 3 months — energy first, then stamina, then solidified results.",
      },
      {
        q: "Best package for first-timers?",
        a: "One bottle to test. Six bottles for lowest per-unit cost.",
      },
    ],
    finalCtaHeadline: "Lock In ErecPrime Before Checkout Resets",
  },
];
